- src/components/dashboard/DashboardBottomWidgets.vue
- src/components/dashboard/users-and-members-tab/UsersMembersTab.vue
- src/components/extra/Extra.vue
- src/components/layout/navbar/Navbar.vue
This ceases demo's load and resolves #10
> Use compressed images for demo

- package.json
It is already listed in the **prod* dependencies
> Remove bootstrap dependency from devDependencies

- src/components/dashboard/setup-profile-tab/SetupProfileTab.vue
- src/components/forms/form-elements/FormElements.vue
- src/components/forms/form-wizard/FormWizard.vue
- src/main.js
The reason for the fields error is veevalidate and vuetable-2 both make use of `fields`, which for whatever reason is not scoped correctly.  
Not totally sure this will compile cause my local project has diverged significantly.
> namespace fix

- src/sass/_material-forms.scss
> Input label centralized within a modal

- README.md
Based on https://github.com/epicmaxco/vuestic-admin/issues/61
> chore(readme): add browser support section

- src/components/forms/form-wizard/FormWizard.vue
Fixing https://github.com/epicmaxco/vuestic-admin/issues/71
> fix(wizard): correct err message

- src/components/vuestic-components/vuestic-wizard/indicators/RichHorizontalIndicator.vue
- src/components/vuestic-components/vuestic-wizard/indicators/RichVerticalIndicator.vue
Fixing https://github.com/epicmaxco/vuestic-admin/issues/78
> fix(wizard): add missing icons

- package.json
Not need changes from last beta 3 update :)
> Only simple update to bootstrap 4.0.0 final

- src/components/vuestic-components/vuestic-modal/VuesticModal.vue
You may need to disable the buttons. eg: to avoid double send a request if double clicked quickly
> Add properties to disable the modal buttons

- src/components/tables/BadgeColumn.vue
This PR fixes ESLint warnings on `badge-column` component.
> fix(badge-column): fix eslint warnings

- src/vuestic-theme/vuestic-components/vuestic-multi-select/VuesticMultiSelect.vue
- src/vuestic-theme/vuestic-components/vuestic-scrollbar/VuesticScrollbar.vue
- src/vuestic-theme/vuestic-components/vuestic-simple-select/VuesticSimpleSelect.vue
Fixes #103 
@smartapant Now it is working fine. Can you double check if I didn't change any other behaviour?
> Set the resize event only when the component is mounted

- src/components/forms/form-elements/FormElements.vue
I found a little confusing the names of the radio groups. I hope this PR helps to those copy-pasting code like me.
> Change radio group names

- src/App.vue
Fixed typo in app selector
Also fixes auth layout. It is quite broken currenly: http://vuestic.epicmax.co/#/auth/login
> Fixed #app height

- build/dev-server.js
Load the favicon in the development environment
> Load the favicon

- src/components/ui/icons/Icons.vue
- src/components/ui/icons/Set.vue
- src/vuestic-theme/vuestic-components/vuestic-slider/VuesticSlider.vue
- src/vuestic-theme/vuestic-plugin.js
This PR closes #123 by extracting the `vuestic-slider` component and refactoring the `set` component.
> feat(components): extract vuestic-slider component

- src/components/forms/form-elements/FormElements.vue
- src/vuestic-theme/vuestic-components/vuestic-checkbox/VuesticCheckbox.vue
- src/vuestic-theme/vuestic-components/vuestic-radio-button/VuesticRadioButton.vue
- src/vuestic-theme/vuestic-components/vuestic-radiobutton/VuesticRadiobutton.vue
- src/vuestic-theme/vuestic-plugin.js
> feat(components) radiobuttons to vuestic-radiobuttons

- package.json
- src/components/dashboard/data-visualisation-tab/DataVisualisation.vue
- src/components/dashboard/data-visualisation-tab/TableData.js
- src/components/tables/Table.vue
- src/vuestic-theme/vuestic-components/vuestic-datatable/VuesticDataTable.vue
- src/vuestic-theme/vuestic-components/vuestic-datatable/datatable-components/FilterBar.vue
- src/vuestic-theme/vuestic-components/vuestic-datatable/datatable-components/ItemsPerPage.vue
this PR closes #130 
What's fixed:
* data mode enabled
* data mode proper filtering
* additional table control slot
* http-fetch and http-options enabled (could be used for handling JWT)
* default per page parameter
> Datatables - data and api mode improvements

- src/components/layout/sidebar/Sidebar.vue
- src/store/modules/menu/statistics.js
> Add icon for submenu

- package.json
- src/components/forms/form-wizard/FormWizard.vue
- src/components/layout/navbar/Navbar.vue
- src/components/ui/tree-view/TreeViewEditablePreview.vue
- src/main.js
- src/sass/_override-custom-libs.scss
- src/vuestic-theme/vuestic-components/vuestic-wizard/VuesticWizard.vue
- yarn.lock
- add polyfill for es6 Promise
- add polyfill for Object.assign
- fix flexbox usage in Form wizard
> IE11 fixes

- src/components/ui/tree-view/TreeViewSelectablePreview.vue
- src/vuestic-theme/vuestic-components/vuestic-checkbox/VuesticCheckbox.vue
- src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeCategory.demo.vue
- src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeCategory.vue
- src/vuestic-theme/vuestic-components/vuestic-tree-view/VuesticTreeNode.vue
Tree category is selectable by default.
closes #216
> Tree node category is clickable by default.

- src/sass/_variables.scss
- src/store/modules/menu/auth.js
- src/store/modules/menu/forms.js
- src/store/modules/menu/maps.js
- src/store/modules/menu/statistics.js
- src/store/modules/menu/ui.js
Only sets icons for children's menu items.
> Sets icons for children's menu items

- src/components/admin/app-navbar/components/dropdowns/ProfileDropdown.vue
- src/components/admin/app-sidebar/AppSidebar.vue
- src/components/admin/app-sidebar/components/SidebarLink.vue
- src/components/auth/login/Login.vue
- src/components/auth/signup/Signup.vue
- src/router/index.js
Related to #190 
* Removed duplicated auth endpoint
* Fixed login/signup issues
* Implemented proper parent-child relations
* Removed absolute paths
> Routing improvements

- src/components/tables/Table.vue
- src/i18n/en.json
- src/i18n/es.json
- src/i18n/pt_br.json
- src/vuestic-theme/vuestic-components/vuestic-datatable/VuesticDataTable.vue
add spinner when data is loading
> feat(data-table): add loader

- src/assets/icons/icon-faster.svg
- src/assets/icons/icon-slower.svg
- src/components/ui/spinners/Spinners.vue
- src/sass/_icons.scss
- src/vuestic-theme/vuestic-components/vuestic-slider/VuesticSlider.vue
> Spinners customization

- src/components/admin/app-sidebar/components/SidebarLinkGroup.vue
https://github.com/epicmaxco/vuestic-admin/issues/283
> Sidebar group click shouldn't hide the menu

- src/vuestic-theme/vuestic-components/vuestic-datatable/VuesticDataTable.vue
> feat(datatable): add proper append-params property

- src/vuestic-theme/vuestic-components/vuestic-datatable/datatable-components/ItemsPerPage.vue
> fix(datatable): extra request on initialization

- src/sass/_override-bootstrap.scss
- src/sass/_variables.scss
> fix(tables): table hover effect on table-striped tables

- package-lock.json
- package.json
>  feat(package): update vee-validate

- src/vuestic-theme/vuestic-components/vuestic-simple-select/VuesticSimpleSelect.vue
- src/vuestic-theme/vuestic-directives/Dropdown.js
It disappeared on dropdown close without select
> fix: select placeholder

- src/vuestic-theme/vuestic-components/vuestic-date-picker/VuesticDatePicker.demo.vue
- src/vuestic-theme/vuestic-components/vuestic-date-picker/VuesticDatePicker.vue
Bug fix: datepicker highlights time with proper bg on hover/focus. Closes #288
> fix(datepicker): datepicker highlights time with proper bg, closes #288

- src/components/maps/google-maps/GoogleMap.vue
> fix(GoogleMap): change version

- src/vuestic-theme/vuestic-sass/global/VuesticLink.demo.vue
- src/vuestic-theme/vuestic-sass/global/_typography.scss
- src/vuestic-theme/vuestic-sass/resources/_variables.scss
close #372
global link class with modifier.
> feat (link): global class with modifier

- src/vuestic-theme/vuestic-components/vuestic-checkbox/VuesticCheckbox.vue
- src/vuestic-theme/vuestic-components/vuestic-radio-button/VuesticRadioButton.vue
> Fix(VuesticRadioButton): change absolute position

- src/vuestic-theme/vuestic-components/va-modal/VaModal.vue
> fix:VaModal fixes

- src/vuestic-theme/vuestic-components/va-checkbox/VaCheckbox.demo.vue
- src/vuestic-theme/vuestic-components/va-checkbox/VaCheckbox.vue
- src/vuestic-theme/vuestic-components/va-checkbox/va-checkbox-docs.md
feat(va-checkbox): add array access to va-checkbox component
close #564 
- Changed va-checkbox wiki in accordance with the new functionality.
- Array access functionality implemented identical to va-toggle component.
- Added a demo of new use.
> feat(va-checkbox): array access

- src/vuestic-theme/vuestic-components/va-checkbox/VaCheckbox.demo.vue
- src/vuestic-theme/vuestic-components/va-checkbox/VaCheckbox.vue
- src/vuestic-theme/vuestic-components/va-checkbox/va-checkbox-docs.md
add a different style for indeterminate checkbox
<details>
```vue
<va-checkbox
v-model="value"
:indeterminate="true"
/>
```
</details>
> feat(VaCheckbox): add indeterminate state

- src/vuestic-theme/vuestic-components/va-input/VaInput.demo.vue
- src/vuestic-theme/vuestic-components/va-input/VaInput.vue
just a suggestion for: https://github.com/epicmaxco/vuestic-admin/issues/510
feel free to edit/discuss.
<details>
```vue
<va-input
v-model="value"
type="textarea"
rows="10"
/>
```
</details>
> feat(VaInput): add type=textarea support

- src/vuestic-theme/vuestic-components/va-button/VaButton.demo.vue
- src/vuestic-theme/vuestic-components/va-button/VaButton.vue
- src/vuestic-theme/vuestic-components/va-chip/VaBadge.vue
- src/vuestic-theme/vuestic-components/va-chip/VaChip.vue
- src/vuestic-theme/vuestic-sass/resources/_variables.scss
fix: badges, chips and buttons heights
see #550
<details>
```vue
// Your code
```
</details>
> fix badge, chip and button outlined heights

- src/components/maps/bubble-maps/BubbleMap.vue
- src/components/maps/bubble-maps/BubbleMapsPage.vue
- src/components/maps/google-maps/GoogleMap.vue
- src/components/maps/google-maps/GoogleMapsPage.vue
- src/components/maps/leaflet-maps/LeafletMap.vue
- src/components/maps/leaflet-maps/LeafletMapsPage.vue
- src/components/maps/line-maps/LineMapsPage.vue
- src/components/maps/yandex-maps/YandexMapsPage.vue
Substitute a couple of `v-bind:`s with `:`s (colons).
<details>
```vue
// Your code
```
</details>
> refator: maps pages refactor

- src/vuestic-theme/vuestic-components/va-button-group/VaButtonGroup.demo.vue
- src/vuestic-theme/vuestic-components/va-button-group/VaButtonGroup.vue
- src/vuestic-theme/vuestic-components/va-button/VaButton.vue
due to complexity of support
Close #520 
<details>
```vue
// Your code
```
</details>
> fix: remove button gradients

- src/vuestic-theme/vuestic-components/va-inner-loading/VaInnerLoading.demo.vue
- src/vuestic-theme/vuestic-components/va-inner-loading/VaInnerLoading.vue
- src/vuestic-theme/vuestic-plugin.js
Shared inner loading component. Useful when loading data inside lists, tables, etc.
> feat(inner-loading): add inner loading component

- src/vuestic-theme/vuestic-components/va-pagination/VaPagination.demo.vue
- src/vuestic-theme/vuestic-components/va-pagination/setPaginationRange.js
- src/vuestic-theme/vuestic-components/va-pagination/setPaginationRange.spec.js
Fixes: https://github.com/epicmaxco/vuestic-admin/issues/560
> Fix/pagination - limit visible pages

- src/components/ui/popovers/Popovers.vue
Hotfix, no issue. Links where not styled, now they are.
<details>
```vue
// Your code
```
</details>
> fix: apply styling to popovers admin page links

- src/components/admin/app-sidebar/components/SidebarLink.vue
- src/components/admin/app-sidebar/components/SidebarLinkGroup.vue
- src/vuestic-theme/vuestic-components/va-sidebar/VaSidebar.vue
> fix: open menu item in a new tab

- src/vuestic-theme/vuestic-components/va-input/VaInput.demo.vue
- src/vuestic-theme/vuestic-components/va-input/VaInput.vue
- src/vuestic-theme/vuestic-components/va-input/calculateNodeHeight.js
Solves #510 
<details>
```vue
// Your code
```
</details>
> feat: textarea autosizing and size restrictions

- src/vuestic-theme/vuestic-components/va-checkbox/KeyboardOnlyFocusMixin.js
- src/vuestic-theme/vuestic-components/va-slider/VaSlider.vue
Close #572 
<details>
```vue
// Your code
```
</details>
> feat: add keys support for sliders

- src/components/admin/app-navbar/components/dropdowns/ColorDropdown.vue
Implementation of requested feature #653
> feat: add button, that allows to revert color changes made from ui

- yarn.lock
> revert yarn lock

- src/components/forms/form-elements/FormElements.vue
- src/components/ui/chat/SetupProfileTab.vue
> fix $validator usage errors

- src/components/statistics/progress-bars/Widgets/ColorfulBars.vue
vue duplicate keys exception
<details>
```vue
// Your code
```
</details>
> vue duplicate keys exception

- package.json
- src/components/statistics/progress-bars/Widgets/ColorfulBars.vue
- yarn.lock
<details>
```vue
// Your code
```
</details>
> update vuestic-ui version

- package.json
- src/app/App.vue
- src/components/admin/AppLayout.vue
- src/components/admin/app-navbar/components/AppNavbarActions.vue
- src/components/admin/app-navbar/components/dropdowns/ColorDropdown.vue
- src/components/dashboard/DashboardInfoBlock.vue
- src/components/dashboard/DashboardTable.vue
- src/components/dashboard/dashboard-tabs/BankDetailsTab.vue
- src/components/lists/Lists.vue
- src/components/pages/404-pages/MadeByComponent.vue
- src/components/pages/404-pages/VaPageNotFoundSearch.vue
- src/components/ui/colors/color-presentation/ColorPresentation.vue
- src/components/ui/notifications/Notifications.vue
- src/components/ui/timelines/Timelines.vue
- src/i18n/en.json
- src/sass/main.scss
- yarn.lock
close #732
close #730
close #729
close #728
close #726
close #724
close #722
close #721
close #720
close #716
<details>
```vue
// Your code
```
</details>
> corporate theme fixes

- src/components/admin/app-navbar/components/dropdowns/LanguageDropdown.vue
- src/i18n/en.json
- src/i18n/index.js
- src/i18n/ir.json
I added Persian language. I'll make it RTL soon.
- [ 1 ] add Persian language
> add Persian language

- package.json
- src/app/main.js
- vue.config.js
- yarn.lock
Closes #756
implement [vue-cli-plugin-build-info](https://github.com/untael/vue-cli-plugin-build-info)
> Fix unsuccessfull project starting, implement build-info plugin

- package.json
- src/components/va-medium-editor/_variables.scss
- src/components/va-medium-editor/va-medium-editor.vue
- src/pages/admin/forms/medium-editor/MediumEditor.vue
- yarn.lock
**BEFORE MERGER THIS PR** you should also merge this PR: https://github.com/epicmaxco/vuestic-ui/pull/823
Also, I have fixed some layout issues and now the medium editor uses ColorConfig colors.
> Move medium editor from vuestic-ui.

- src/pages/admin/forms/form-elements/FormElements.vue
close epicmaxco/vuestic-admin#826 
**Before:**
**After:**
> Fix #826: Checkbox examples

- src/components/navbar/components/AppNavbarActions.vue
- src/components/navbar/components/dropdowns/MessageDropdown.vue
- src/components/navbar/components/dropdowns/NotificationDropdown.vue
- src/data/charts/BubbleChartData.ts
- src/data/charts/LineChartData.ts
- src/data/charts/types/index.ts
- src/data/maps/BubbleMapData.ts
- src/main.ts
- src/pages/admin/tables/data-tables/scenarios/DataTableInfiniteScroll.vue
- src/pages/admin/ui/chat/StickyScroll.ts
- src/services/vuestic-ui/themes.ts
> fix: typing and remove unused imports

- src/i18n/cn.json
- src/main.ts
Fix i18n Chinese flag.
Add Persian Chinese translation
<details>
```vue
// Your code
cn.json:
"language": {
"brazilian_portuguese": "葡萄牙语",
"english": "英语",
"spanish": "西班牙语",
"simplified_chinese": "简体中文",
"persian": "波斯语" ←
}
main.ts:
ch: require('@/i18n/cn.json'), → cn: require('@/i18n/cn.json'),
```
</details>
> Fix Chinese

- package-lock.json
- package.json
- yarn.lock
> Build: bump vuestic-ui from 1.4.10 to 1.4.13

- package-lock.json
- package.json
- src/components/sidebar/NavigationRoutes.ts
- src/pages/admin/ui/route.ts
- src/pages/admin/ui/spinners/Spinners.vue
- yarn.lock
> Feat: add `epic-spinners` component

- src/pages/auth/login/Login.vue
<details>
```vue
// Your code
```
</details>
> login error use router

- src/layouts/AppLayout.vue
Fixed navbar and navbar menu on mobile screens. Should be applied alongside this PR:
https://github.com/epicmaxco/vuestic-ui/pull/2835
> fix: mobile screen navbar and menu

- src/pages/admin/dashboard/Dashboard.vue
close #932 
I added a sloppy privacy policy for now. Maybe later we can do something better.
> feat: add privacy policy

- src/router/index.ts
- yarn.lock
See #929 
The necessary changes were made in the router configuration to achieve this result. Changed '/admin' to '/' 
- [+] Bug fix (non-breaking change which fixes an issue)
> Refactor router configuration to remove 'admin' from URL paths

- index.html
- src/App.vue
- src/components/va-charts/vaChartConfigs.js
> chore: swap font. Source Pro -> Inter (#940)

- src/layouts/RouterBypass.vue
- src/pages/admin/pages/404PagesPage.vue
- src/router/index.ts
- tailwind.config.js
- redirect for root path to dashboard
- set max-width for pages content
closes #946, closes #948
> page content max-width, redirect fix root to dashboard

- yarn.lock
close #951
- it's showing now(localy), some deps problem ¯\_(ツ)_/¯
> Navbar return (#951)

- package.json
- src/pages/preferences/modals/EditNameModal.vue
- src/pages/preferences/modals/ResetPasswordModal.vue
- src/pages/preferences/preferences-header/PreferencesHeader.vue
- src/pages/preferences/settings/Settings.vue
- yarn.lock
close https://github.com/epicmaxco/vuestic-admin/issues/936
Fixes specifically - https://github.com/epicmaxco/vuestic-admin/issues/936#issuecomment-1820468027
edit modal:
reset password modal:
Colour change for button:
reset password mobile version:
<details>
```vue
// Your code
```
</details>
> Improve Preferences page

- src/components/VuesticLogo.vue
- src/components/navbar/AppNavbar.vue
- src/components/navbar/components/AppNavbarActions.vue
- src/components/navbar/components/dropdowns/NotificationDropdown.vue
- src/components/navbar/components/dropdowns/ProfileDropdown.vue
- src/i18n/locales/gb.json
close https://github.com/epicmaxco/vuestic-admin/issues/996
> Header tweaks

- src/components/app-layout-navigation/AppLayoutNavigation.vue
close https://github.com/epicmaxco/vuestic-admin/issues/991
> revert breadcrumb change

- README.md
Updates readme with "Support & Consulting" page info
> Update readme with "Support & Consulting" page info

- src/components/va-medium-editor/VaMediumEditor.vue
Fixes #1003
<details>
```vue
$medium-editor-background-color: var(--va-background-primary);
```
</details>
> fix readability of medium-editor toolbar

- src/components/va-medium-editor/VaMediumEditor.vue
- yarn.lock
[fix readability of medium-editor toolbar (](https://github.com/epicmaxco/vuestic-admin/commit/6b57d520c24629f4d12d57465ef2ce4f02953c4d)https://github.com/epicmaxco/vuestic-admin/pull/1004[)](https://github.com/epicmaxco/vuestic-admin/commit/6b57d520c24629f4d12d57465ef2ce4f02953c4d)
> fix: medium editor

- src/data/pages/projects.ts
- src/data/pages/users.ts
- src/pages/admin/dashboard/cards/ProjectTable.vue
- src/pages/projects/ProjectsPage.vue
- src/pages/projects/composables/useProjectUsers.ts
- src/pages/projects/composables/useProjects.ts
- src/pages/projects/types.ts
- src/pages/projects/widgets/EditProjectForm.vue
- src/pages/projects/widgets/ProjectCards.vue
- src/pages/projects/widgets/ProjectsTable.vue
- src/pages/users/UsersPage.vue
- src/pages/users/composables/useUsers.ts
- src/pages/users/types.ts
- src/pages/users/widgets/EditUserForm.vue
- src/pages/users/widgets/UserAvatar.vue
- src/pages/users/widgets/UsersTable.vue
- src/services/api.ts
- src/stores/projects.ts
- src/stores/users.ts
- vite.config.ts
Implements integration with Projects API
> feat: connect Projects to the backend

- src/data/pages/projects.ts
- src/data/pages/users.ts
- src/pages/projects/composables/useProjects.ts
- src/pages/projects/widgets/ProjectCards.vue
- src/pages/projects/widgets/ProjectsTable.vue
- src/pages/users/composables/useUsers.ts
- src/stores/projects.ts
- src/stores/users.ts
Fixes pagination/sorting bugs after Projects API integration
> fix: move sorting/pagination to hooks

- package.json
- src/data/pages/users.ts
- src/pages/users/UsersPage.vue
- src/pages/users/composables/useUsers.ts
- src/pages/users/widgets/UserAvatar.vue
- src/services/api.ts
- src/stores/users.ts
- yarn.lock
Implements avatars API integration
> feat: implement files uploading integration
